[gcp_service_account]
type = "service_account"
project_id = "copia_del_json..."
private_key_id = "copia_del_json..."
private_key = "copia_del_json..."
client_email = "copia_del_json..."
client_id = "copia_del_json..."
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "copia_del_json..."
